from __future__ import annotations

import ast
import json
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .storage import ensure_dir, read_json, write_json


GENERATED_NOTICE = "<!-- generated by src/conversation_os/codebase_overview.py; do not edit by hand -->"
OVERVIEW_FILENAME = "CODEBASE_OVERVIEW.md"
MAP_FILENAME = "codebase_map.json"
AGENT_BRIEF_FILENAME = "AGENT_OPERATING_BRIEF.md"
TRACKED_ROOTS = [
    ("src/conversation_os", {".py"}),
    ("tools", {".py"}),
]
TRACKED_SINGLE_FILES = [
    "AGENTS.md",
    "PRODUCT_THESIS.md",
    "SESSION_PROTOCOL.md",
    "CONTEXT_ROUTING.md",
]
IGNORED_PARTS = {"__pycache__", ".git", ".pytest_cache", ".mypy_cache", ".vendor", "node_modules"}
AGENT_SURFACE_LINKS = [
    ("Repo Entry", "../../README.md"),
    ("Agent Rules", "../../AGENTS.md"),
    ("Product Thesis", "../../PRODUCT_THESIS.md"),
    ("Codebase Overview", "./CODEBASE_OVERVIEW.md"),
    ("Substrate Agent Index", "./AGENT_INDEX.md"),
]
ARCHITECTURE_LINKS = [
    ("Conversation OS Foundation Design", "../../docs/plans/2026-04-13-conversation-os-foundation-design.md"),
    ("Inner World OpenClaw Server Architecture", "../../docs/plans/2026-04-14-inner-world-openclaw-server-architecture.md"),
    ("Bounded OpenClaw Semantic Assist Architecture", "../../docs/plans/2026-04-23-bounded-openclaw-semantic-assist-architecture.md"),
]
REPO_PATH_LINKS = [
    ("Conversation Runtime", "../../src/conversation_os/"),
    ("Inner World Product", "../../product/inner_world_v1/"),
    ("OpenClaw Deployment Tooling", "../../tools/"),
    ("Architecture Docs", "../../docs/plans/"),
    ("Substrate Context", "../../context/substrate/"),
]
QUICK_OWNER_PATHS = [
    "src/conversation_os/cli.py",
    "src/conversation_os/product_inner_world.py",
    "src/conversation_os/chat_backends.py",
    "src/conversation_os/openclaw_miniapp.py",
    "tools/deploy_inner_world_to_openclaw.py",
]


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def _overview_dir(root: Path) -> Path:
    return root / "context" / "substrate"


def _overview_path(root: Path) -> Path:
    return _overview_dir(root) / OVERVIEW_FILENAME


def _map_path(root: Path) -> Path:
    return _overview_dir(root) / MAP_FILENAME


def _agent_brief_path(root: Path) -> Path:
    return _overview_dir(root) / AGENT_BRIEF_FILENAME


def _safe_read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="utf-8", errors="ignore")


def _python_entry(root: Path, path: Path) -> dict[str, Any]:
    text = _safe_read_text(path)
    relative = str(path.relative_to(root))
    tree = ast.parse(text)
    symbols = [
        node.name
        for node in tree.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
    ]
    imports_internal: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            if node.module.startswith("conversation_os") or node.module.startswith("src.conversation_os"):
                imports_internal.append(node.module)
            elif node.level and node.module:
                imports_internal.append(node.module)
        elif isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name.startswith("conversation_os") or alias.name.startswith("src.conversation_os"):
                    imports_internal.append(alias.name)
    docstring = ast.get_docstring(tree) or ""
    if not docstring:
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("#") and not stripped.startswith("#!"):
                docstring = stripped.lstrip("#").strip()
                break
    area = relative.split("/", 2)[1] if relative.startswith("src/") and relative.count("/") >= 2 else relative.split("/", 1)[0]
    return {
        "path": relative,
        "kind": "python",
        "area": area,
        "summary": docstring or f"Python module at {relative}.",
        "symbols": symbols[:12],
        "imports_internal": sorted(set(imports_internal)),
    }


def _markdown_entry(root: Path, path: Path) -> dict[str, Any]:
    text = _safe_read_text(path)
    relative = str(path.relative_to(root))
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    summary = ""
    for line in lines:
        if line.startswith("#"):
            continue
        summary = line
        break
    area = relative.split("/", 1)[0]
    return {
        "path": relative,
        "kind": "document",
        "area": area,
        "summary": summary or f"Document at {relative}.",
        "symbols": [],
        "imports_internal": [],
    }


def _iter_tracked_paths(root: Path) -> list[Path]:
    paths: list[Path] = []
    for relative_root, suffixes in TRACKED_ROOTS:
        base = root / relative_root
        if not base.exists():
            continue
        for path in sorted(base.rglob("*")):
            if not path.is_file():
                continue
            if any(part in IGNORED_PARTS for part in path.parts):
                continue
            if path.suffix in suffixes:
                paths.append(path)
    for relative_path in TRACKED_SINGLE_FILES:
        path = root / relative_path
        if path.exists():
            paths.append(path)
    return paths


def build_codebase_map(root: Path) -> dict[str, Any]:
    entries: list[dict[str, Any]] = []
    for path in _iter_tracked_paths(root):
        if path.suffix == ".py":
            entries.append(_python_entry(root, path))
        else:
            entries.append(_markdown_entry(root, path))

    area_counter = Counter(entry["area"] for entry in entries)
    return {
        "generated_at": utc_now(),
        "entry_count": len(entries),
        "areas": dict(sorted(area_counter.items())),
        "entries": entries,
    }


def render_codebase_overview(payload: dict[str, Any]) -> str:
    by_area: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for entry in payload["entries"]:
        by_area[entry["area"]].append(entry)

    lines = [
        GENERATED_NOTICE,
        "# Codebase Overview",
        "",
        f"- generated_at: {payload['generated_at']}",
        f"- entry_count: {payload['entry_count']}",
        f"- area_count: {len(by_area)}",
        "",
        "## Areas",
        "",
    ]
    for area, count in sorted(payload["areas"].items()):
        lines.append(f"- `{area}`: {count} tracked files")

    lines.extend(["", "## Modules", ""])
    for area in sorted(by_area):
        lines.append(f"### {area}")
        lines.append("")
        for entry in sorted(by_area[area], key=lambda row: row["path"]):
            lines.append(f"- `{entry['path']}`")
            lines.append(f"  - kind: {entry['kind']}")
            lines.append(f"  - summary: {entry['summary']}")
            if entry["symbols"]:
                lines.append(f"  - symbols: {', '.join(entry['symbols'][:6])}")
            if entry["imports_internal"]:
                lines.append(f"  - internal_imports: {', '.join(entry['imports_internal'][:4])}")
        lines.append("")
    return "\n".join(lines)


def render_agent_operating_brief(payload: dict[str, Any]) -> str:
    entry_lookup = {entry["path"]: entry for entry in payload["entries"]}
    lines = [
        GENERATED_NOTICE,
        "# Agent Operating Brief",
        "",
        f"- generated_at: {payload['generated_at']}",
        "- refresh_trigger: `python tools/conversation_os.py repo-overview refresh`",
        "- deploy_trigger: `python tools/deploy_inner_world_to_openclaw.py` refreshes this brief before syncing to OpenClaw",
        "",
        "## Canonical Surfaces",
        "",
    ]
    for label, href in AGENT_SURFACE_LINKS:
        lines.append(f"- [{label}]({href})")

    lines.extend(["", "## Architecture Links", ""])
    for label, href in ARCHITECTURE_LINKS:
        lines.append(f"- [{label}]({href})")

    lines.extend(["", "## Repo Paths", ""])
    for label, href in REPO_PATH_LINKS:
        lines.append(f"- [{label}]({href})")

    lines.extend(["", "## Tracked Areas", ""])
    for area, count in sorted(payload["areas"].items()):
        lines.append(f"- `{area}`: {count} tracked files")

    lines.extend(["", "## Quick Owners", ""])
    for path in QUICK_OWNER_PATHS:
        entry = entry_lookup.get(path)
        if entry is None:
            continue
        lines.append(f"- `{path}`")
        lines.append(f"  - {entry['summary']}")
    return "\n".join(lines)


def refresh_codebase_overview(root: Path) -> dict[str, Any]:
    ensure_dir(_overview_dir(root))
    payload = build_codebase_map(root)
    write_json(_map_path(root), payload)
    _overview_path(root).write_text(render_codebase_overview(payload).rstrip() + "\n", encoding="utf-8")
    _agent_brief_path(root).write_text(render_agent_operating_brief(payload).rstrip() + "\n", encoding="utf-8")
    return {
        "generated_at": payload["generated_at"],
        "entry_count": payload["entry_count"],
        "overview_path": str(_overview_path(root)),
        "map_path": str(_map_path(root)),
        "agent_brief_path": str(_agent_brief_path(root)),
    }


def load_codebase_map(root: Path) -> dict[str, Any]:
    payload = read_json(_map_path(root), default=None)
    if payload is None:
        refresh_codebase_overview(root)
        payload = read_json(_map_path(root), default={"generated_at": utc_now(), "entry_count": 0, "areas": {}, "entries": []})
    return payload


def lookup_codebase(root: Path, query: str, limit: int = 8) -> list[dict[str, Any]]:
    payload = load_codebase_map(root)
    tokens = [token.lower() for token in query.replace("_", " ").split() if token.strip()]
    scored: list[dict[str, Any]] = []
    for entry in payload["entries"]:
        haystack = " ".join(
            [
                entry["path"],
                entry["summary"],
                " ".join(entry.get("symbols", [])),
                " ".join(entry.get("imports_internal", [])),
            ]
        ).lower()
        score = 0
        matched_tokens: list[str] = []
        for token in tokens:
            if token in haystack:
                score += 1
                matched_tokens.append(token)
            if token in entry["path"].lower():
                score += 2
            if token in entry["summary"].lower():
                score += 1
        if score <= 0:
            continue
        scored.append(
            {
                "path": entry["path"],
                "kind": entry["kind"],
                "area": entry["area"],
                "summary": entry["summary"],
                "symbols": entry.get("symbols", []),
                "score": score,
                "matched_tokens": sorted(set(matched_tokens)),
            }
        )
    scored.sort(key=lambda row: (-row["score"], row["path"]))
    return scored[:limit]
