from __future__ import annotations

import ast
import hashlib
import json
import time
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .storage import ensure_dir, read_json, write_json


MODULE_ID = "builder.codebase.codebase_overview"
CONTRACT_VERSION = "1.0"
PUBLIC_API = (
    "MODULE_ID",
    "CONTRACT_VERSION",
    "utc_now",
    "load_module_manifests",
    "inspect_codebase_index",
    "build_codebase_map",
    "render_codebase_overview",
    "render_codebase_atlas",
    "render_agent_operating_brief",
    "refresh_codebase_overview",
    "validate_codebase_index",
    "watch_codebase_overview",
    "load_codebase_map",
    "lookup_codebase",
)
__all__ = list(PUBLIC_API)


GENERATED_NOTICE = "<!-- generated by src/conversation_os/codebase_overview.py; do not edit by hand -->"
OVERVIEW_FILENAME = "CODEBASE_OVERVIEW.md"
ATLAS_FILENAME = "CODEBASE_ATLAS.md"
MAP_FILENAME = "codebase_map.json"
AGENT_BRIEF_FILENAME = "AGENT_OPERATING_BRIEF.md"
MODULES_DIRNAME = "modules"
REGISTRY_DIRNAME = "registry"
MODULE_REGISTRY_FILENAME = "module_registry.json"
MODULE_BROWSE_FILENAME = "module_browse_map.json"
DEPENDENCY_GRAPH_FILENAME = "dependency_graph.json"
SURFACE_INDEX_FILENAME = "surface_index.json"
OWNER_INDEX_FILENAME = "owner_index.json"
TRACKED_ROOTS = [
    ("src/conversation_os", {".py"}),
    ("tools", {".py"}),
]
TRACKED_SINGLE_FILES = [
    "AGENTS.md",
    "PRODUCT_THESIS.md",
    "SESSION_PROTOCOL.md",
    "CONTEXT_ROUTING.md",
]
IGNORED_PARTS = {"__pycache__", ".git", ".pytest_cache", ".mypy_cache", ".vendor", "node_modules"}
MANIFEST_REQUIRED_FIELDS = {
    "module_id": str,
    "path": str,
    "layer": str,
    "owner": str,
    "purpose": str,
    "status": str,
    "version": str,
    "public_api": list,
    "contains": list,
    "depends_on": list,
    "feeds_into": list,
    "inputs": list,
    "outputs": list,
    "state_owned": list,
    "surfaces_using": list,
}
MANIFEST_RECOMMENDED_FIELDS = {
    "compatibility_wrappers": list,
    "notes": str,
    "adjacent_docs": list,
    "gitnexus_hints": list,
    "test_targets": list,
    "constraints": list,
}
ALLOWED_LAYERS = {"kernel", "assembly", "surface", "builder-support", "tooling", "document"}
ALLOWED_STATUSES = {"active", "compatibility", "experimental", "legacy"}
MANIFEST_EXEMPT_PATHS = {
    "src/conversation_os/__init__.py",
    "src/conversation_os/services/__init__.py",
    "src/conversation_os/vault_adapters/__init__.py",
}
AGENT_SURFACE_LINKS = [
    ("Repo Entry", "../../README.md"),
    ("Agent Rules", "../../AGENTS.md"),
    ("Product Thesis", "../../PRODUCT_THESIS.md"),
    ("Codebase Overview", "./CODEBASE_OVERVIEW.md"),
    ("Codebase Atlas", "./CODEBASE_ATLAS.md"),
    ("Substrate Agent Index", "./AGENT_INDEX.md"),
]
ARCHITECTURE_LINKS = [
    ("Conversation OS Foundation Design", "../../docs/plans/2026-04-13-conversation-os-foundation-design.md"),
    ("Inner World OpenClaw Server Architecture", "../../docs/plans/2026-04-14-inner-world-openclaw-server-architecture.md"),
    ("Bounded OpenClaw Semantic Assist Architecture", "../../docs/plans/2026-04-23-bounded-openclaw-semantic-assist-architecture.md"),
]
REPO_PATH_LINKS = [
    ("Conversation Runtime", "../../src/conversation_os/"),
    ("Inner World Product", "../../product/inner_world_v1/"),
    ("OpenClaw Deployment Tooling", "../../tools/"),
    ("Architecture Docs", "../../docs/plans/"),
    ("Substrate Context", "../../context/substrate/"),
]
QUICK_OWNER_PATHS = [
    "src/conversation_os/cli.py",
    "src/conversation_os/product_inner_world.py",
    "src/conversation_os/chat_backends.py",
    "src/conversation_os/openclaw_miniapp.py",
    "tools/deploy_inner_world_to_openclaw.py",
]


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def _overview_dir(root: Path) -> Path:
    return root / "context" / "substrate"


def _overview_path(root: Path) -> Path:
    return _overview_dir(root) / OVERVIEW_FILENAME


def _map_path(root: Path) -> Path:
    return _overview_dir(root) / MAP_FILENAME


def _atlas_path(root: Path) -> Path:
    return _overview_dir(root) / ATLAS_FILENAME


def _agent_brief_path(root: Path) -> Path:
    return _overview_dir(root) / AGENT_BRIEF_FILENAME


def _modules_dir(root: Path) -> Path:
    return _overview_dir(root) / MODULES_DIRNAME


def _registry_dir(root: Path) -> Path:
    return _overview_dir(root) / REGISTRY_DIRNAME


def _module_registry_path(root: Path) -> Path:
    return _registry_dir(root) / MODULE_REGISTRY_FILENAME


def _module_browse_path(root: Path) -> Path:
    return _registry_dir(root) / MODULE_BROWSE_FILENAME


def _dependency_graph_path(root: Path) -> Path:
    return _registry_dir(root) / DEPENDENCY_GRAPH_FILENAME


def _surface_index_path(root: Path) -> Path:
    return _registry_dir(root) / SURFACE_INDEX_FILENAME


def _owner_index_path(root: Path) -> Path:
    return _registry_dir(root) / OWNER_INDEX_FILENAME


def _generated_artifact_paths(root: Path) -> list[Path]:
    return [
        _overview_path(root),
        _atlas_path(root),
        _map_path(root),
        _agent_brief_path(root),
        _module_registry_path(root),
        _module_browse_path(root),
        _dependency_graph_path(root),
        _surface_index_path(root),
        _owner_index_path(root),
    ]


def _tracked_input_paths(root: Path) -> list[Path]:
    return sorted(_iter_tracked_paths(root) + list(_modules_dir(root).glob("*.json")))


def _codebase_input_fingerprint(root: Path) -> str:
    digest = hashlib.sha256()
    for path in _tracked_input_paths(root):
        if not path.exists():
            continue
        digest.update(str(path.relative_to(root)).encode("utf-8"))
        stat = path.stat()
        digest.update(str(stat.st_mtime_ns).encode("utf-8"))
        digest.update(str(stat.st_size).encode("utf-8"))
    return digest.hexdigest()


def _safe_read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="utf-8", errors="ignore")


def _python_entry(root: Path, path: Path) -> dict[str, Any]:
    text = _safe_read_text(path)
    relative = str(path.relative_to(root))
    tree = ast.parse(text)
    symbols = [
        node.name
        for node in tree.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
    ]
    imports_internal: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            if node.module.startswith("conversation_os") or node.module.startswith("src.conversation_os"):
                imports_internal.append(node.module)
            elif node.level and node.module:
                imports_internal.append(node.module)
        elif isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name.startswith("conversation_os") or alias.name.startswith("src.conversation_os"):
                    imports_internal.append(alias.name)
    docstring = ast.get_docstring(tree) or ""
    if not docstring:
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("#") and not stripped.startswith("#!"):
                docstring = stripped.lstrip("#").strip()
                break
    area = relative.split("/", 2)[1] if relative.startswith("src/") and relative.count("/") >= 2 else relative.split("/", 1)[0]
    return {
        "path": relative,
        "kind": "python",
        "area": area,
        "summary": docstring or f"Python module at {relative}.",
        "symbols": symbols[:12],
        "imports_internal": sorted(set(imports_internal)),
    }


def _markdown_entry(root: Path, path: Path) -> dict[str, Any]:
    text = _safe_read_text(path)
    relative = str(path.relative_to(root))
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    summary = ""
    for line in lines:
        if line.startswith("#"):
            continue
        summary = line
        break
    area = relative.split("/", 1)[0]
    return {
        "path": relative,
        "kind": "document",
        "area": area,
        "summary": summary or f"Document at {relative}.",
        "symbols": [],
        "imports_internal": [],
    }


def _iter_tracked_paths(root: Path) -> list[Path]:
    paths: list[Path] = []
    for relative_root, suffixes in TRACKED_ROOTS:
        base = root / relative_root
        if not base.exists():
            continue
        for path in sorted(base.rglob("*")):
            if not path.is_file():
                continue
            if any(part in IGNORED_PARTS for part in path.parts):
                continue
            if path.suffix in suffixes:
                paths.append(path)
    for relative_path in TRACKED_SINGLE_FILES:
        path = root / relative_path
        if path.exists():
            paths.append(path)
    return paths


def _is_list_of_strings(value: Any) -> bool:
    return isinstance(value, list) and all(isinstance(item, str) for item in value)


def _validate_manifest(root: Path, path: Path, payload: dict[str, Any]) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    relative = str(path.relative_to(root))
    for field, expected_type in MANIFEST_REQUIRED_FIELDS.items():
        if field not in payload:
            errors.append(f"{relative}: missing required field `{field}`")
            continue
        value = payload[field]
        if expected_type is list:
            if not _is_list_of_strings(value):
                errors.append(f"{relative}: field `{field}` must be a list of strings")
        elif not isinstance(value, expected_type):
            errors.append(f"{relative}: field `{field}` must be `{expected_type.__name__}`")

    for field, expected_type in MANIFEST_RECOMMENDED_FIELDS.items():
        if field not in payload:
            continue
        value = payload[field]
        if expected_type is list:
            if not _is_list_of_strings(value):
                errors.append(f"{relative}: field `{field}` must be a list of strings")
        elif not isinstance(value, expected_type):
            errors.append(f"{relative}: field `{field}` must be `{expected_type.__name__}`")

    layer = payload.get("layer")
    if isinstance(layer, str) and layer not in ALLOWED_LAYERS:
        errors.append(f"{relative}: layer `{layer}` is not allowed")
    status = payload.get("status")
    if isinstance(status, str) and status not in ALLOWED_STATUSES:
        errors.append(f"{relative}: status `{status}` is not allowed")

    module_path = payload.get("path")
    if isinstance(module_path, str):
        source_path = root / module_path
        if not source_path.exists():
            errors.append(f"{relative}: declared path `{module_path}` does not exist")

    compatibility_wrappers = payload.get("compatibility_wrappers", [])
    if status == "compatibility" and not compatibility_wrappers:
        warnings.append(f"{relative}: compatibility manifest does not declare any `compatibility_wrappers`")

    return errors, warnings


def load_module_manifests(root: Path) -> dict[str, Any]:
    manifests: list[dict[str, Any]] = []
    errors: list[str] = []
    warnings: list[str] = []
    by_path: dict[str, dict[str, Any]] = {}
    modules_dir = _modules_dir(root)
    for manifest_path in sorted(modules_dir.glob("*.json")):
        payload = read_json(manifest_path, default=None)
        if not isinstance(payload, dict):
            errors.append(f"{manifest_path.relative_to(root)}: manifest payload must be a JSON object")
            continue
        manifest_errors, manifest_warnings = _validate_manifest(root, manifest_path, payload)
        errors.extend(manifest_errors)
        warnings.extend(manifest_warnings)
        if manifest_errors:
            continue
        payload["manifest_path"] = str(manifest_path.relative_to(root))
        manifests.append(payload)
        declared_path = payload.get("path")
        if isinstance(declared_path, str):
            by_path[declared_path] = payload

    tracked_python_paths = [
        str(path.relative_to(root))
        for path in _iter_tracked_paths(root)
        if path.suffix == ".py" and str(path.relative_to(root)) not in MANIFEST_EXEMPT_PATHS
    ]
    missing_paths = sorted(path for path in tracked_python_paths if path not in by_path)
    if missing_paths:
        preview = ", ".join(missing_paths[:8])
        suffix = " ..." if len(missing_paths) > 8 else ""
        warnings.append(f"{len(missing_paths)} tracked python modules do not yet have manifests: {preview}{suffix}")

    known_ids = {
        manifest["module_id"]
        for manifest in manifests
        if isinstance(manifest.get("module_id"), str)
    }
    for manifest in manifests:
        for dependency in manifest.get("depends_on", []):
            if dependency.startswith("external:") or dependency in known_ids:
                continue
            warnings.append(
                f"{manifest['manifest_path']}: dependency `{dependency}` does not resolve to a manifest in the current tranche"
            )
        for consumer in manifest.get("feeds_into", []):
            if consumer.startswith("external:") or consumer in known_ids:
                continue
            warnings.append(
                f"{manifest['manifest_path']}: downstream reference `{consumer}` does not resolve to a manifest in the current tranche"
            )

    return {
        "generated_at": utc_now(),
        "manifest_count": len(manifests),
        "manifests": manifests,
        "by_path": by_path,
        "errors": errors,
        "warnings": warnings,
        "missing_paths": missing_paths,
    }


def inspect_codebase_index(root: Path) -> dict[str, Any]:
    tracked_inputs = _tracked_input_paths(root)
    generated_paths = _generated_artifact_paths(root)

    newest_source_path = ""
    newest_source_mtime = 0.0
    for path in tracked_inputs:
        try:
            mtime = path.stat().st_mtime
        except FileNotFoundError:
            continue
        if mtime >= newest_source_mtime:
            newest_source_mtime = mtime
            newest_source_path = str(path.relative_to(root))

    missing_artifacts = [str(path.relative_to(root)) for path in generated_paths if not path.exists()]

    newest_generated_path = ""
    newest_generated_mtime = 0.0
    stale_reasons: list[str] = []
    if missing_artifacts:
        stale_reasons.append(
            "Generated codebase artifacts are missing: " + ", ".join(missing_artifacts)
        )
    else:
        newest_generated = max(generated_paths, key=lambda path: path.stat().st_mtime)
        newest_generated_mtime = newest_generated.stat().st_mtime
        newest_generated_path = str(newest_generated.relative_to(root))
        if newest_source_mtime > newest_generated_mtime:
            stale_reasons.append(
                "Generated codebase artifacts are older than the newest tracked source or manifest "
                f"({newest_generated_path} < {newest_source_path})."
            )

    return {
        "generated_at": utc_now(),
        "tracked_input_count": len(tracked_inputs),
        "generated_artifact_count": len(generated_paths),
        "fresh": not stale_reasons,
        "stale_reasons": stale_reasons,
        "missing_artifacts": missing_artifacts,
        "newest_source_path": newest_source_path,
        "newest_source_mtime": newest_source_mtime,
        "newest_generated_path": newest_generated_path,
        "newest_generated_mtime": newest_generated_mtime,
    }


def _render_module_registry(module_index: dict[str, Any]) -> dict[str, Any]:
    return {
        "generated_at": module_index["generated_at"],
        "manifest_count": module_index["manifest_count"],
        "errors": module_index["errors"],
        "warnings": module_index["warnings"],
        "missing_paths": module_index["missing_paths"],
        "manifests": module_index["manifests"],
    }


def _render_module_browse_map(module_index: dict[str, Any]) -> dict[str, Any]:
    layers: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for manifest in module_index["manifests"]:
        layers[manifest["layer"]].append(
            {
                "module_id": manifest["module_id"],
                "path": manifest["path"],
                "status": manifest["status"],
                "purpose": manifest["purpose"],
                "owner": manifest["owner"],
            }
        )
    return {
        "generated_at": module_index["generated_at"],
        "manifest_count": module_index["manifest_count"],
        "layers": {layer: sorted(entries, key=lambda row: row["module_id"]) for layer, entries in sorted(layers.items())},
    }


def _render_dependency_graph(module_index: dict[str, Any]) -> dict[str, Any]:
    manifests = module_index["manifests"]
    known_ids = {manifest["module_id"] for manifest in manifests}
    nodes = [
        {
            "module_id": manifest["module_id"],
            "path": manifest["path"],
            "layer": manifest["layer"],
            "status": manifest["status"],
            "owner": manifest["owner"],
        }
        for manifest in manifests
    ]
    edges: list[dict[str, Any]] = []
    for manifest in manifests:
        source = manifest["module_id"]
        for target in manifest.get("depends_on", []):
            edges.append(
                {
                    "source": source,
                    "target": target,
                    "kind": "depends_on",
                    "external": target not in known_ids,
                }
            )
        for target in manifest.get("feeds_into", []):
            edges.append(
                {
                    "source": source,
                    "target": target,
                    "kind": "feeds_into",
                    "external": target not in known_ids,
                }
            )
    return {
        "generated_at": module_index["generated_at"],
        "node_count": len(nodes),
        "edge_count": len(edges),
        "nodes": nodes,
        "edges": edges,
    }


def _render_surface_index(module_index: dict[str, Any]) -> dict[str, Any]:
    surfaces: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for manifest in module_index["manifests"]:
        for surface in manifest.get("surfaces_using", []):
            surfaces[surface].append(
                {
                    "module_id": manifest["module_id"],
                    "path": manifest["path"],
                    "layer": manifest["layer"],
                    "status": manifest["status"],
                }
            )
    return {
        "generated_at": module_index["generated_at"],
        "surface_count": len(surfaces),
        "surfaces": {
            surface: sorted(entries, key=lambda row: row["module_id"])
            for surface, entries in sorted(surfaces.items())
        },
    }


def _render_owner_index(module_index: dict[str, Any]) -> dict[str, Any]:
    owners: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for manifest in module_index["manifests"]:
        owners[manifest["owner"]].append(
            {
                "module_id": manifest["module_id"],
                "path": manifest["path"],
                "layer": manifest["layer"],
                "status": manifest["status"],
            }
        )
    return {
        "generated_at": module_index["generated_at"],
        "owner_count": len(owners),
        "owners": {
            owner: sorted(entries, key=lambda row: row["module_id"])
            for owner, entries in sorted(owners.items())
        },
    }


def build_codebase_map(root: Path) -> dict[str, Any]:
    module_index = load_module_manifests(root)
    entries: list[dict[str, Any]] = []
    for path in _iter_tracked_paths(root):
        if path.suffix == ".py":
            entry = _python_entry(root, path)
        else:
            entry = _markdown_entry(root, path)
        manifest = module_index["by_path"].get(entry["path"])
        if manifest is not None:
            entry["module_manifest"] = {
                "module_id": manifest["module_id"],
                "layer": manifest["layer"],
                "status": manifest["status"],
                "owner": manifest["owner"],
                "purpose": manifest["purpose"],
            }
        entries.append(entry)

    area_counter = Counter(entry["area"] for entry in entries)
    return {
        "generated_at": utc_now(),
        "entry_count": len(entries),
        "areas": dict(sorted(area_counter.items())),
        "module_manifest_count": module_index["manifest_count"],
        "module_manifest_errors": module_index["errors"],
        "module_manifest_warnings": module_index["warnings"],
        "module_manifest_missing_paths": module_index["missing_paths"],
        "module_index": _render_module_registry(module_index),
        "entries": entries,
    }


def render_codebase_overview(payload: dict[str, Any]) -> str:
    by_area: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for entry in payload["entries"]:
        by_area[entry["area"]].append(entry)

    lines = [
        GENERATED_NOTICE,
        "# Codebase Overview",
        "",
        f"- generated_at: {payload['generated_at']}",
        f"- entry_count: {payload['entry_count']}",
        f"- area_count: {len(by_area)}",
        f"- module_manifest_count: {payload.get('module_manifest_count', 0)}",
        f"- module_manifest_error_count: {len(payload.get('module_manifest_errors', []))}",
        f"- module_manifest_warning_count: {len(payload.get('module_manifest_warnings', []))}",
        "",
        "## Areas",
        "",
    ]
    for area, count in sorted(payload["areas"].items()):
        lines.append(f"- `{area}`: {count} tracked files")

    lines.extend(["", "## Modules", ""])
    for area in sorted(by_area):
        lines.append(f"### {area}")
        lines.append("")
        for entry in sorted(by_area[area], key=lambda row: row["path"]):
            lines.append(f"- `{entry['path']}`")
            lines.append(f"  - kind: {entry['kind']}")
            lines.append(f"  - summary: {entry['summary']}")
            if entry.get("module_manifest"):
                manifest = entry["module_manifest"]
                lines.append(
                    f"  - manifest: {manifest['module_id']} [{manifest['layer']}, {manifest['status']}]"
                )
            if entry["symbols"]:
                lines.append(f"  - symbols: {', '.join(entry['symbols'][:6])}")
            if entry["imports_internal"]:
                lines.append(f"  - internal_imports: {', '.join(entry['imports_internal'][:4])}")
        lines.append("")
    return "\n".join(lines)


def render_codebase_atlas(payload: dict[str, Any]) -> str:
    entry_lookup = {entry["path"]: entry for entry in payload["entries"]}
    manifests = payload["module_index"]["manifests"]
    by_layer: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for manifest in manifests:
        by_layer[manifest["layer"]].append(manifest)

    lines = [
        GENERATED_NOTICE,
        "# Codebase Atlas",
        "",
        f"- generated_at: {payload['generated_at']}",
        f"- module_manifest_count: {payload.get('module_manifest_count', 0)}",
        f"- tracked_entry_count: {payload['entry_count']}",
        "",
        "## Layers",
        "",
    ]
    for layer in sorted(by_layer):
        lines.append(f"- `{layer}`: {len(by_layer[layer])} modules")

    lines.extend(["", "## Modules", ""])
    for layer in sorted(by_layer):
        lines.append(f"### {layer}")
        lines.append("")
        for manifest in sorted(by_layer[layer], key=lambda row: row["module_id"]):
            entry = entry_lookup.get(manifest["path"], {})
            lines.append(f"#### `{manifest['module_id']}`")
            lines.append("")
            lines.append(f"- path: `{manifest['path']}`")
            lines.append(f"- status: `{manifest['status']}`")
            lines.append(f"- owner: {manifest['owner']}")
            lines.append(f"- purpose: {manifest['purpose']}")
            if manifest.get("public_api"):
                lines.append(f"- public_api: {', '.join(manifest['public_api'][:12])}")
            if manifest.get("contains"):
                lines.append(f"- contains: {', '.join(manifest['contains'][:8])}")
            if manifest.get("depends_on"):
                lines.append(f"- depends_on: {', '.join(manifest['depends_on'][:10])}")
            if manifest.get("feeds_into"):
                lines.append(f"- feeds_into: {', '.join(manifest['feeds_into'][:10])}")
            if manifest.get("surfaces_using"):
                lines.append(f"- surfaces_using: {', '.join(manifest['surfaces_using'])}")
            if manifest.get("state_owned"):
                lines.append(f"- state_owned: {', '.join(manifest['state_owned'][:8])}")
            if manifest.get("compatibility_wrappers"):
                lines.append(f"- compatibility_wrappers: {', '.join(manifest['compatibility_wrappers'][:8])}")
            if entry.get("symbols"):
                lines.append(f"- symbols: {', '.join(entry['symbols'][:10])}")
            if entry.get("imports_internal"):
                lines.append(f"- internal_imports: {', '.join(entry['imports_internal'][:10])}")
            if manifest.get("test_targets"):
                lines.append(f"- test_targets: {', '.join(manifest['test_targets'])}")
            lines.append("")
    return "\n".join(lines)


def render_agent_operating_brief(payload: dict[str, Any]) -> str:
    entry_lookup = {entry["path"]: entry for entry in payload["entries"]}
    lines = [
        GENERATED_NOTICE,
        "# Agent Operating Brief",
        "",
        f"- generated_at: {payload['generated_at']}",
        "- refresh_trigger: `python tools/conversation_os.py repo-overview refresh`",
        "- validate_trigger: `python tools/conversation_os.py repo-overview validate`",
        "- watch_helper: `python3 -c \"from pathlib import Path; from conversation_os.codebase_overview import watch_codebase_overview; watch_codebase_overview(Path('.').resolve(), interval=2.0)\"`",
        "- deploy_trigger: `python tools/deploy_inner_world_to_openclaw.py` refreshes this brief before syncing to OpenClaw",
        f"- module_manifest_count: {payload.get('module_manifest_count', 0)}",
        "",
        "## Canonical Surfaces",
        "",
    ]
    for label, href in AGENT_SURFACE_LINKS:
        lines.append(f"- [{label}]({href})")

    lines.extend(["", "## Architecture Links", ""])
    for label, href in ARCHITECTURE_LINKS:
        lines.append(f"- [{label}]({href})")

    lines.extend(["", "## Repo Paths", ""])
    for label, href in REPO_PATH_LINKS:
        lines.append(f"- [{label}]({href})")

    lines.extend(["", "## Tracked Areas", ""])
    for area, count in sorted(payload["areas"].items()):
        lines.append(f"- `{area}`: {count} tracked files")

    lines.extend(["", "## Quick Owners", ""])
    for path in QUICK_OWNER_PATHS:
        entry = entry_lookup.get(path)
        if entry is None:
            continue
        lines.append(f"- `{path}`")
        lines.append(f"  - {entry['summary']}")
    lines.extend(
        [
            "",
            "## Index Discipline",
            "",
            "- Run `repo-overview refresh` before substantial implementation work so generated atlas and registry surfaces stay current.",
            "- Run `repo-overview validate` after substantive ownership or manifest edits; do not treat the module atlas as ready if validation reports stale artifacts, manifest errors, warnings, or missing coverage.",
        ]
    )
    return "\n".join(lines)


def refresh_codebase_overview(root: Path) -> dict[str, Any]:
    ensure_dir(_overview_dir(root))
    ensure_dir(_registry_dir(root))
    payload = build_codebase_map(root)
    write_json(_map_path(root), payload)
    write_json(_module_registry_path(root), payload["module_index"])
    write_json(_module_browse_path(root), _render_module_browse_map(payload["module_index"]))
    write_json(_dependency_graph_path(root), _render_dependency_graph(payload["module_index"]))
    write_json(_surface_index_path(root), _render_surface_index(payload["module_index"]))
    write_json(_owner_index_path(root), _render_owner_index(payload["module_index"]))
    _overview_path(root).write_text(render_codebase_overview(payload).rstrip() + "\n", encoding="utf-8")
    _atlas_path(root).write_text(render_codebase_atlas(payload).rstrip() + "\n", encoding="utf-8")
    _agent_brief_path(root).write_text(render_agent_operating_brief(payload).rstrip() + "\n", encoding="utf-8")
    return {
        "generated_at": payload["generated_at"],
        "entry_count": payload["entry_count"],
        "module_manifest_count": payload.get("module_manifest_count", 0),
        "module_manifest_error_count": len(payload.get("module_manifest_errors", [])),
        "module_manifest_warning_count": len(payload.get("module_manifest_warnings", [])),
        "overview_path": str(_overview_path(root)),
        "atlas_path": str(_atlas_path(root)),
        "map_path": str(_map_path(root)),
        "agent_brief_path": str(_agent_brief_path(root)),
        "module_registry_path": str(_module_registry_path(root)),
        "module_browse_map_path": str(_module_browse_path(root)),
        "dependency_graph_path": str(_dependency_graph_path(root)),
        "surface_index_path": str(_surface_index_path(root)),
        "owner_index_path": str(_owner_index_path(root)),
    }


def validate_codebase_index(root: Path) -> dict[str, Any]:
    module_index = load_module_manifests(root)
    freshness = inspect_codebase_index(root)
    return {
        "generated_at": module_index["generated_at"],
        "module_manifest_count": module_index["manifest_count"],
        "error_count": len(module_index["errors"]),
        "warning_count": len(module_index["warnings"]),
        "missing_manifest_count": len(module_index["missing_paths"]),
        "fresh": freshness["fresh"],
        "stale_reasons": freshness["stale_reasons"],
        "missing_artifacts": freshness["missing_artifacts"],
        "newest_source_path": freshness["newest_source_path"],
        "newest_generated_path": freshness["newest_generated_path"],
        "errors": module_index["errors"],
        "warnings": module_index["warnings"],
        "missing_paths": module_index["missing_paths"],
    }


def watch_codebase_overview(root: Path, interval: float = 2.0, max_iterations: int | None = None) -> dict[str, Any]:
    last_result = refresh_codebase_overview(root)
    last_fingerprint = _codebase_input_fingerprint(root)
    refresh_count = 1
    iterations = 0

    while max_iterations is None or iterations < max_iterations:
        time.sleep(interval)
        iterations += 1
        current = _codebase_input_fingerprint(root)
        if current == last_fingerprint:
            continue
        last_result = refresh_codebase_overview(root)
        last_fingerprint = current
        refresh_count += 1

    return {
        "generated_at": utc_now(),
        "refresh_count": refresh_count,
        "iterations": iterations,
        "last_fingerprint": last_fingerprint,
        "last_result": last_result,
    }


def load_codebase_map(root: Path) -> dict[str, Any]:
    payload = read_json(_map_path(root), default=None)
    if payload is None:
        refresh_codebase_overview(root)
        payload = read_json(_map_path(root), default={"generated_at": utc_now(), "entry_count": 0, "areas": {}, "entries": []})
    return payload


def _normalized_lookup_token(value: str) -> str:
    return value.strip().lower().replace("_", " ")


def _parse_lookup_query(query: str) -> tuple[dict[str, list[str]], list[str]]:
    supported_filters = {"layer", "owner", "surface", "module", "status", "path", "area", "kind"}
    filters: dict[str, list[str]] = defaultdict(list)
    free_tokens: list[str] = []
    for raw_token in query.split():
        token = raw_token.strip()
        if not token:
            continue
        if ":" in token:
            key, value = token.split(":", 1)
            key = key.strip().lower()
            value = _normalized_lookup_token(value)
            if key in supported_filters and value:
                filters[key].append(value)
                continue
        free_tokens.append(_normalized_lookup_token(token))
    return dict(filters), free_tokens


def _entry_matches_lookup_filters(entry: dict[str, Any], manifest: dict[str, Any], filters: dict[str, list[str]]) -> bool:
    surface_values = [_normalized_lookup_token(value) for value in manifest.get("surfaces_using", [])]
    candidates = {
        "layer": _normalized_lookup_token(manifest.get("layer", "")),
        "owner": _normalized_lookup_token(manifest.get("owner", "")),
        "status": _normalized_lookup_token(manifest.get("status", "")),
        "module": _normalized_lookup_token(manifest.get("module_id", "")),
        "path": _normalized_lookup_token(entry.get("path", "")),
        "area": _normalized_lookup_token(entry.get("area", "")),
        "kind": _normalized_lookup_token(entry.get("kind", "")),
    }
    for key, expected_values in filters.items():
        if key == "surface":
            if not all(any(expected in surface for surface in surface_values) for expected in expected_values):
                return False
            continue
        candidate = candidates.get(key, "")
        if not all(expected in candidate for expected in expected_values):
            return False
    return True


def lookup_codebase(root: Path, query: str, limit: int = 8) -> list[dict[str, Any]]:
    payload = load_codebase_map(root)
    manifests_by_path = {
        manifest["path"]: manifest
        for manifest in payload.get("module_index", {}).get("manifests", [])
        if isinstance(manifest, dict) and isinstance(manifest.get("path"), str)
    }
    filters, tokens = _parse_lookup_query(query)
    scored: list[dict[str, Any]] = []
    for entry in payload["entries"]:
        manifest = manifests_by_path.get(entry["path"], {})
        if filters and not _entry_matches_lookup_filters(entry, manifest, filters):
            continue
        haystack = " ".join(
            [
                entry["path"],
                entry["summary"],
                " ".join(entry.get("symbols", [])),
                " ".join(entry.get("imports_internal", [])),
                manifest.get("module_id", entry.get("module_manifest", {}).get("module_id", "")),
                manifest.get("layer", entry.get("module_manifest", {}).get("layer", "")),
                manifest.get("status", entry.get("module_manifest", {}).get("status", "")),
                manifest.get("owner", entry.get("module_manifest", {}).get("owner", "")),
                manifest.get("purpose", entry.get("module_manifest", {}).get("purpose", "")),
                " ".join(manifest.get("surfaces_using", [])),
            ]
        ).lower()
        score = len(filters) * 3 if filters else 0
        matched_tokens: list[str] = []
        for token in tokens:
            if token in haystack:
                score += 1
                matched_tokens.append(token)
            if token in entry["path"].lower():
                score += 2
            if token in entry["summary"].lower():
                score += 1
        if score <= 0:
            continue
        scored.append(
            {
                "path": entry["path"],
                "kind": entry["kind"],
                "area": entry["area"],
                "summary": entry["summary"],
                "symbols": entry.get("symbols", []),
                "module_manifest": entry.get("module_manifest"),
                "score": score,
                "matched_tokens": sorted(set(matched_tokens)),
            }
        )
    scored.sort(key=lambda row: (-row["score"], row["path"]))
    return scored[:limit]
