from __future__ import annotations

import hashlib
import os
import subprocess
import time
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .storage import ensure_dir, read_json, write_json, write_markdown


MODULE_ID = "builder.codebase.repo_index"
CONTRACT_VERSION = "1.0"
PUBLIC_API = (
    "MODULE_ID",
    "CONTRACT_VERSION",
    "classify_repo_path",
    "refresh_repo_index",
    "validate_repo_index",
    "get_repo_index_health",
    "watch_repo_index",
    "build_runtime_migration_plan",
)
__all__ = list(PUBLIC_API)


GENERATED_NOTICE = "<!-- generated by src/conversation_os/repo_index.py; do not edit by hand -->"
REPO_INDEX_FILENAME = "repo_index.json"
DOCS_INDEX_FILENAME = "docs_index.json"
PRODUCT_SURFACE_INDEX_FILENAME = "product_surface_index.json"
STATE_BOUNDARY_INDEX_FILENAME = "state_boundary_index.json"
ARTIFACT_INDEX_FILENAME = "artifact_index.json"
MIGRATION_CANDIDATES_FILENAME = "migration_candidates.json"
RUNTIME_MIGRATION_PLAN_FILENAME = "runtime_migration_plan.json"
REPO_ORGANIZATION_FILENAME = "REPO_ORGANIZATION.md"
RUNTIME_MIGRATION_PLAN_MD_FILENAME = "RUNTIME_MIGRATION_PLAN.md"
INDEX_FILENAMES = (
    REPO_INDEX_FILENAME,
    DOCS_INDEX_FILENAME,
    PRODUCT_SURFACE_INDEX_FILENAME,
    STATE_BOUNDARY_INDEX_FILENAME,
    ARTIFACT_INDEX_FILENAME,
    MIGRATION_CANDIDATES_FILENAME,
    RUNTIME_MIGRATION_PLAN_FILENAME,
)
IGNORED_PARTS = {".git", "__pycache__", ".pytest_cache", ".mypy_cache", "node_modules"}
TOP_LEVEL_RUNTIME_DIRS = {"memory", "vaults", "output", "outputs", "tmp", "runtime"}
TOP_LEVEL_ARTIFACT_DIRS = {"mobile_artifacts", "artifacts"}
DOC_ARCHIVE_PARTS = {"transcripts", "building-diary"}


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def _substrate_dir(root: Path) -> Path:
    return root / "context" / "substrate"


def _registry_dir(root: Path) -> Path:
    return _substrate_dir(root) / "registry"


def _repo_index_path(root: Path) -> Path:
    return _registry_dir(root) / REPO_INDEX_FILENAME


def _docs_index_path(root: Path) -> Path:
    return _registry_dir(root) / DOCS_INDEX_FILENAME


def _product_surface_index_path(root: Path) -> Path:
    return _registry_dir(root) / PRODUCT_SURFACE_INDEX_FILENAME


def _state_boundary_index_path(root: Path) -> Path:
    return _registry_dir(root) / STATE_BOUNDARY_INDEX_FILENAME


def _artifact_index_path(root: Path) -> Path:
    return _registry_dir(root) / ARTIFACT_INDEX_FILENAME


def _repo_organization_path(root: Path) -> Path:
    return _substrate_dir(root) / REPO_ORGANIZATION_FILENAME


def _migration_candidates_path(root: Path) -> Path:
    return _registry_dir(root) / MIGRATION_CANDIDATES_FILENAME


def _runtime_migration_plan_path(root: Path) -> Path:
    return _registry_dir(root) / RUNTIME_MIGRATION_PLAN_FILENAME


def _runtime_migration_plan_md_path(root: Path) -> Path:
    return _substrate_dir(root) / RUNTIME_MIGRATION_PLAN_MD_FILENAME


def _generated_artifact_paths(root: Path) -> list[Path]:
    return [
        _repo_index_path(root),
        _docs_index_path(root),
        _product_surface_index_path(root),
        _state_boundary_index_path(root),
        _artifact_index_path(root),
        _migration_candidates_path(root),
        _repo_organization_path(root),
        _runtime_migration_plan_path(root),
        _runtime_migration_plan_md_path(root),
    ]


def _generated_artifact_relatives(root: Path) -> set[str]:
    return {str(path.relative_to(root)) for path in _generated_artifact_paths(root)}


def _fingerprint_for_paths(root: Path, relative_paths: list[str]) -> str:
    digest = hashlib.sha256()
    for relative in relative_paths:
        path = root / relative
        if not path.exists():
            continue
        stat = path.stat()
        digest.update(relative.encode("utf-8"))
        digest.update(str(stat.st_mtime_ns).encode("utf-8"))
        digest.update(str(stat.st_size).encode("utf-8"))
    return digest.hexdigest()


def _git_tracked_paths(root: Path) -> list[str]:
    try:
        result = subprocess.run(
            ["git", "ls-files"],
            cwd=root,
            check=True,
            capture_output=True,
            text=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return []
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def _walk_repo_paths(root: Path) -> list[str]:
    paths: set[str] = set()
    for child in root.iterdir():
        relative = child.relative_to(root)
        if child.name in IGNORED_PARTS:
            continue
        if child.is_file():
            paths.add(str(relative))
            continue
        if child.name in TOP_LEVEL_RUNTIME_DIRS | TOP_LEVEL_ARTIFACT_DIRS:
            paths.add(str(relative))
            for grandchild in sorted(child.iterdir()):
                paths.add(str(grandchild.relative_to(root)))
            continue
        if child.name == "product":
            for product_dir in sorted(child.iterdir()):
                if not product_dir.is_dir():
                    paths.add(str(product_dir.relative_to(root)))
                    continue
                for current_root, dirnames, filenames in os.walk(product_dir):
                    dirnames[:] = [dirname for dirname in dirnames if dirname not in IGNORED_PARTS]
                    current_path = Path(current_root)
                    rel_current = current_path.relative_to(root)
                    if current_path.name in {"data", "runs", "exports", "backups", "portable", "openclaw_bundle"}:
                        paths.add(str(rel_current))
                        for dirname in dirnames:
                            paths.add(str((current_path / dirname).relative_to(root)))
                        for filename in filenames:
                            paths.add(str((current_path / filename).relative_to(root)))
                        dirnames[:] = []
                        continue
                    for filename in filenames:
                        paths.add(str((current_path / filename).relative_to(root)))
            continue
        for current_root, dirnames, filenames in os.walk(child):
            dirnames[:] = [dirname for dirname in dirnames if dirname not in IGNORED_PARTS]
            current_path = Path(current_root)
            for filename in filenames:
                paths.add(str((current_path / filename).relative_to(root)))
    return sorted(paths)


def _boundary_markers(root: Path) -> list[str]:
    markers: set[str] = set()
    for dirname in sorted(TOP_LEVEL_RUNTIME_DIRS | TOP_LEVEL_ARTIFACT_DIRS):
        base = root / dirname
        if not base.exists():
            continue
        markers.add(dirname)
        for child in sorted(base.iterdir()):
            markers.add(str(child.relative_to(root)))
    product_root = root / "product"
    if not product_root.exists():
        return sorted(markers)
    for product_dir in sorted(product_root.iterdir()):
        if not product_dir.is_dir():
            continue
        for runtime_dir in ("data", "runs", "exports", "backups", "portable", "openclaw_bundle"):
            base = product_dir / runtime_dir
            if not base.exists():
                continue
            markers.add(str(base.relative_to(root)))
            for child in sorted(base.iterdir()):
                markers.add(str(child.relative_to(root)))
    return sorted(markers)


def _repo_paths(root: Path) -> list[str]:
    tracked = _git_tracked_paths(root)
    if tracked:
        return sorted(set(tracked + _boundary_markers(root)))
    return _walk_repo_paths(root)


def _input_repo_paths(root: Path) -> list[str]:
    generated = _generated_artifact_relatives(root)
    return [relative for relative in _repo_paths(root) if relative not in generated]


def classify_repo_path(relative_path: str) -> dict[str, Any]:
    parts = Path(relative_path).parts
    if not parts:
        return {"class": "unclassified", "reason": "empty_path"}

    first = parts[0]
    if first == "src" or (first == "tools" and relative_path.endswith(".py")):
        return {"class": "source", "reason": "implementation_code"}
    if first == "tests":
        return {"class": "source", "reason": "test_code"}
    if relative_path in {
        "AGENTS.md",
        "PRODUCT_THESIS.md",
        "SESSION_PROTOCOL.md",
        "CONTEXT_ROUTING.md",
        "TENETS.md",
        "README.md",
        "pyproject.toml",
        ".gitignore",
        ".gitattributes",
    }:
        return {"class": "contract", "reason": "repo_contract"}
    if first == "context":
        if len(parts) >= 3 and parts[1] == "substrate" and parts[2] == "modules":
            return {"class": "contract", "reason": "module_manifest"}
        if len(parts) >= 3 and parts[1] == "substrate" and parts[2] == "registry":
            return {"class": "generated_index", "reason": "generated_registry"}
        if len(parts) >= 2 and parts[1] == "substrate":
            return {"class": "generated_index", "reason": "substrate_summary"}
        return {"class": "runtime_state", "reason": "context_workspace_state"}
    if first == "docs":
        if any(part in DOC_ARCHIVE_PARTS for part in parts[1:]):
            return {"class": "archive", "reason": "historical_docs"}
        return {"class": "docs", "reason": "documentation"}
    if first == "product":
        if len(parts) >= 3 and parts[2] in {"data", "runs", "exports", "backups", "portable", "openclaw_bundle"}:
            return {"class": "runtime_state", "reason": f"product_runtime:{parts[2]}"}
        if len(parts) >= 3 and parts[2] == "config":
            return {"class": "contract", "reason": "product_config"}
        return {"class": "source", "reason": "product_surface_source"}
    if first in TOP_LEVEL_RUNTIME_DIRS:
        return {"class": "runtime_state", "reason": f"top_level_runtime:{first}"}
    if first in TOP_LEVEL_ARTIFACT_DIRS:
        return {"class": "artifact", "reason": f"top_level_artifact:{first}"}
    if first in {"pipelines", "plugins", "ops"}:
        return {"class": "source", "reason": "supporting_source"}
    if first == "frameworks synthesis":
        return {"class": "docs", "reason": "research_docs"}
    return {"class": "unclassified", "reason": "fallback"}


def _build_docs_index(entries: list[dict[str, Any]]) -> dict[str, Any]:
    docs_by_bucket: dict[str, list[str]] = defaultdict(list)
    for entry in entries:
        if entry["class"] not in {"docs", "archive"}:
            continue
        relative = entry["path"]
        parts = Path(relative).parts
        bucket = parts[1] if len(parts) > 1 and parts[0] == "docs" else "misc"
        docs_by_bucket[bucket].append(relative)
    return {
        "generated_at": utc_now(),
        "buckets": {key: sorted(value) for key, value in sorted(docs_by_bucket.items())},
    }


def _build_product_surface_index(entries: list[dict[str, Any]]) -> dict[str, Any]:
    products: dict[str, dict[str, list[str]]] = defaultdict(lambda: defaultdict(list))
    for entry in entries:
        parts = Path(entry["path"]).parts
        if len(parts) < 2 or parts[0] != "product":
            continue
        products[parts[1]][entry["class"]].append(entry["path"])
    return {
        "generated_at": utc_now(),
        "products": {
            product: {bucket: sorted(paths) for bucket, paths in sorted(buckets.items())}
            for product, buckets in sorted(products.items())
        },
    }


def _build_state_boundary_index(entries: list[dict[str, Any]]) -> dict[str, Any]:
    grouped: dict[str, list[str]] = defaultdict(list)
    for entry in entries:
        if entry["class"] != "runtime_state":
            continue
        grouped[entry["reason"]].append(entry["path"])
    return {
        "generated_at": utc_now(),
        "boundaries": {key: sorted(value) for key, value in sorted(grouped.items())},
    }


def _build_artifact_index(entries: list[dict[str, Any]]) -> dict[str, Any]:
    grouped: dict[str, list[str]] = defaultdict(list)
    for entry in entries:
        if entry["class"] not in {"artifact", "generated_index"}:
            continue
        grouped[entry["class"]].append(entry["path"])
    return {
        "generated_at": utc_now(),
        "artifacts": {key: sorted(value) for key, value in sorted(grouped.items())},
    }


def _build_migration_candidates(entries: list[dict[str, Any]]) -> dict[str, Any]:
    docs_archive_candidates: list[str] = []
    root_doc_candidates: list[str] = []
    product_runtime_candidates: list[str] = []
    context_generated_candidates: list[str] = []

    for entry in entries:
        relative = entry["path"]
        classification = entry["class"]
        parts = Path(relative).parts
        if classification == "archive":
            docs_archive_candidates.append(relative)
        if classification == "docs" and len(parts) == 1 and relative.endswith(".md"):
            root_doc_candidates.append(relative)
        if classification == "runtime_state" and relative.startswith("product/"):
            product_runtime_candidates.append(relative)
        if classification == "generated_index" and relative.startswith("context/substrate/"):
            context_generated_candidates.append(relative)

    return {
        "generated_at": utc_now(),
        "docs_archive_candidates": sorted(docs_archive_candidates),
        "root_doc_candidates": sorted(root_doc_candidates),
        "product_runtime_candidates": sorted(product_runtime_candidates),
        "context_generated_candidates": sorted(context_generated_candidates),
    }


def _runtime_move_target(product_name: str, runtime_dir: str) -> tuple[str, str]:
    if runtime_dir in {"data", "runs"}:
        return "runtime_state", f"runtime/product_state/{product_name}/{runtime_dir}"
    if runtime_dir in {"exports", "portable", "openclaw_bundle"}:
        return "artifact", f"artifacts/exports/{product_name}/{runtime_dir}"
    if runtime_dir == "backups":
        return "artifact", f"artifacts/backups/{product_name}/{runtime_dir}"
    return "runtime_state", f"runtime/product_state/{product_name}/{runtime_dir}"


def build_runtime_migration_plan(root: Path) -> dict[str, Any]:
    moves: list[dict[str, Any]] = []
    product_root = root / "product"
    if product_root.exists():
        for product_dir in sorted(product_root.iterdir()):
            if not product_dir.is_dir():
                continue
            for runtime_dir in ("data", "runs", "exports", "backups", "portable", "openclaw_bundle"):
                source = product_dir / runtime_dir
                if not source.exists():
                    continue
                move_class, target = _runtime_move_target(product_dir.name, runtime_dir)
                moves.append(
                    {
                        "source": str(source.relative_to(root)),
                        "target": target,
                        "class": move_class,
                        "strategy": "directory_family_move",
                        "status": "proposed",
                    }
                )

    tranches = [
        {
            "tranche_id": "tranche-1-runtime-state",
            "goal": "Move live mutable product state out of product source trees.",
            "includes": [move for move in moves if move["class"] == "runtime_state"],
        },
        {
            "tranche_id": "tranche-2-artifacts",
            "goal": "Move export, backup, and portable artifact families under artifacts/.",
            "includes": [move for move in moves if move["class"] == "artifact"],
        },
        {
            "tranche_id": "tranche-3-docs-archive",
            "goal": "Normalize historical docs into explicit archive locations after runtime boundaries are clean.",
            "includes": [],
        },
    ]
    plan = {
        "generated_at": utc_now(),
        "status": "proposed",
        "directory_moves": moves,
        "tranches": tranches,
        "non_goals": [
            "Do not move src/, tests/, tools/, product configs, pipelines, or miniapp source in this tranche.",
            "Do not change imports or runtime readers until relocation shims are designed.",
        ],
        "target_roots": [
            "runtime/product_state/",
            "artifacts/exports/",
            "artifacts/backups/",
        ],
    }
    write_json(_runtime_migration_plan_path(root), plan)
    write_markdown(_runtime_migration_plan_md_path(root), _render_runtime_migration_plan(plan))
    return plan


def _render_runtime_migration_plan(plan: dict[str, Any]) -> str:
    lines = [
        GENERATED_NOTICE,
        "",
        "# Runtime Migration Plan",
        "",
        f"- Generated at: `{plan['generated_at']}`",
        f"- Status: `{plan['status']}`",
        f"- Directory moves: `{len(plan['directory_moves'])}`",
        "",
        "## Tranches",
        "",
    ]
    for tranche in plan["tranches"]:
        lines.append(f"### {tranche['tranche_id']}")
        lines.append("")
        lines.append(f"- Goal: {tranche['goal']}")
        lines.append(f"- Move count: `{len(tranche['includes'])}`")
        lines.append("")
    lines.extend(["## Proposed Moves", ""])
    for move in plan["directory_moves"]:
        lines.append(f"- `{move['source']}` -> `{move['target']}` ({move['class']})")
    lines.extend(["", "## Non-Goals", ""])
    for item in plan["non_goals"]:
        lines.append(f"- {item}")
    return "\n".join(lines)


def _render_repo_organization(summary: dict[str, Any], validation: dict[str, Any]) -> str:
    lines = [
        GENERATED_NOTICE,
        "",
        "# Repo Organization",
        "",
        f"- Generated at: `{summary['generated_at']}`",
        f"- Classified paths: `{summary['classified_path_count']}`",
        f"- Unclassified paths: `{summary['unclassified_path_count']}`",
        "",
        "## Class Counts",
        "",
    ]
    for key, value in summary["class_counts"].items():
        lines.append(f"- `{key}`: {value}")
    lines.extend(
        [
            "",
            "## Validation",
            "",
            f"- Fresh: `{validation['fresh']}`",
            f"- Missing artifacts: `{len(validation['missing_artifacts'])}`",
            f"- Unclassified paths: `{len(validation['unclassified_paths'])}`",
        ]
    )
    return "\n".join(lines)


def refresh_repo_index(root: Path) -> dict[str, Any]:
    relative_paths = _input_repo_paths(root)
    entries: list[dict[str, Any]] = []
    counts: Counter[str] = Counter()
    unclassified: list[str] = []
    for relative in relative_paths:
        classification = classify_repo_path(relative)
        entry = {"path": relative, **classification}
        entries.append(entry)
        counts[classification["class"]] += 1
        if classification["class"] == "unclassified":
            unclassified.append(relative)

    fingerprint = _fingerprint_for_paths(root, relative_paths)
    summary = {
        "generated_at": utc_now(),
        "fingerprint": fingerprint,
        "classified_path_count": len(entries),
        "unclassified_path_count": len(unclassified),
        "class_counts": dict(sorted(counts.items())),
    }
    repo_index = {"summary": summary, "entries": entries}
    docs_index = _build_docs_index(entries)
    product_surface_index = _build_product_surface_index(entries)
    state_boundary_index = _build_state_boundary_index(entries)
    artifact_index = _build_artifact_index(entries)
    migration_candidates = _build_migration_candidates(entries)
    runtime_migration_plan = build_runtime_migration_plan(root)

    write_json(_repo_index_path(root), repo_index)
    write_json(_docs_index_path(root), docs_index)
    write_json(_product_surface_index_path(root), product_surface_index)
    write_json(_state_boundary_index_path(root), state_boundary_index)
    write_json(_artifact_index_path(root), artifact_index)
    write_json(_migration_candidates_path(root), migration_candidates)
    write_json(_runtime_migration_plan_path(root), runtime_migration_plan)
    write_markdown(
        _repo_organization_path(root),
        _render_repo_organization(
            summary,
            {
                "fresh": False,
                "missing_artifacts": [],
                "unclassified_paths": unclassified,
            },
        ),
    )

    validation = validate_repo_index(root)
    write_markdown(_repo_organization_path(root), _render_repo_organization(summary, validation))
    write_markdown(_runtime_migration_plan_md_path(root), _render_runtime_migration_plan(runtime_migration_plan))

    return {
        "summary": summary,
        "paths": {name: str(_registry_dir(root) / name) for name in INDEX_FILENAMES} | {"organization": str(_repo_organization_path(root))},
        "validation": validation,
        "migration_candidates": migration_candidates,
        "runtime_migration_plan": runtime_migration_plan,
    }


def validate_repo_index(root: Path) -> dict[str, Any]:
    relative_paths = _input_repo_paths(root)
    missing_artifacts = [str(path.relative_to(root)) for path in _generated_artifact_paths(root) if not path.exists()]
    generated_times = [path.stat().st_mtime_ns for path in _generated_artifact_paths(root) if path.exists()]
    newest_source_time = max((root / relative).stat().st_mtime_ns for relative in relative_paths) if relative_paths else 0
    stale = bool(generated_times) and max(generated_times) < newest_source_time

    repo_index = read_json(_repo_index_path(root), default={}) or {}
    entries = repo_index.get("entries", [])
    existing_entry_map = {entry.get("path"): entry for entry in entries if isinstance(entry, dict)}
    unclassified_paths = []
    missing_paths = []
    for relative in relative_paths:
        entry = existing_entry_map.get(relative)
        if not entry:
            missing_paths.append(relative)
            continue
        if entry.get("class") == "unclassified":
            unclassified_paths.append(relative)

    fresh = not missing_artifacts and not stale and not missing_paths and not unclassified_paths
    return {
        "fresh": fresh,
        "missing_artifacts": missing_artifacts,
        "stale": stale,
        "missing_paths": missing_paths,
        "unclassified_paths": unclassified_paths,
    }


def get_repo_index_health(root: Path) -> dict[str, Any]:
    validation = validate_repo_index(root)
    repo_index = read_json(_repo_index_path(root), default={}) or {}
    migration_candidates = read_json(_migration_candidates_path(root), default={}) or {}
    runtime_migration_plan = read_json(_runtime_migration_plan_path(root), default={}) or {}
    summary = repo_index.get("summary", {})
    return {
        "fresh": validation["fresh"],
        "summary": summary,
        "missing_artifacts": validation["missing_artifacts"],
        "unclassified_paths": validation["unclassified_paths"],
        "missing_paths": validation["missing_paths"],
        "migration_candidates": migration_candidates,
        "runtime_migration_plan": runtime_migration_plan,
    }


def watch_repo_index(root: Path, interval: float = 2.0, max_iterations: int | None = None) -> dict[str, Any]:
    last_result = refresh_repo_index(root)
    last_fingerprint = last_result["summary"]["fingerprint"]
    refresh_count = 1
    iterations = 0

    while max_iterations is None or iterations < max_iterations:
        time.sleep(interval)
        iterations += 1
        current_paths = _input_repo_paths(root)
        current_fingerprint = _fingerprint_for_paths(root, current_paths)
        if current_fingerprint == last_fingerprint:
            continue
        last_result = refresh_repo_index(root)
        last_fingerprint = last_result["summary"]["fingerprint"]
        refresh_count += 1

    return {
        "generated_at": utc_now(),
        "refresh_count": refresh_count,
        "iterations": iterations,
        "last_fingerprint": last_fingerprint,
        "last_result": last_result,
    }
