#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import time
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SUBSTRATE_ROOT = ROOT / "context" / "substrate"
FAMILIES_ROOT = SUBSTRATE_ROOT / "families"
PURPOSE_ROOT = SUBSTRATE_ROOT / "generated" / "purpose"
GENERATED_NOTICE = "<!-- generated by tools/substrate_index.py; do not edit by hand -->"
REQUIRED_MANIFEST_FIELDS = ("id", "title", "family", "purpose", "extracts", "depends_on", "feeds_into")


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def read_preview(path: Path) -> str:
    if not path.exists():
        return ""
    lines = path.read_text(encoding="utf-8").splitlines()
    in_body = False
    paragraph: list[str] = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            if paragraph:
                break
            continue
        if stripped.startswith("# "):
            in_body = True
            continue
        if not in_body:
            continue
        if stripped.startswith("#"):
            continue
        paragraph.append(stripped)
    return " ".join(paragraph).strip()


def family_summary(family: str) -> str:
    summaries = {
        "framing": "Orient content before any richer reasoning takes place.",
        "structure": "Project content into explicit substrate objects and process stages.",
        "governance": "Preserve decisions, defaults, and protected boundaries.",
        "tension": "Make pressure, tradeoffs, and contradictions first-class.",
        "epistemics": "Attach support, uncertainty, and missingness.",
        "transfer": "Extract reusable patterns and where they can travel."
    }
    return summaries.get(family, "")


def _validate_manifest(manifest_path: Path, manifest: dict) -> list[str]:
    errors: list[str] = []
    for field in REQUIRED_MANIFEST_FIELDS:
        if field not in manifest:
            errors.append(f"{manifest_path}: missing required field `{field}`")
    for field in ("extracts", "depends_on", "feeds_into"):
        value = manifest.get(field)
        if value is not None and not isinstance(value, list):
            errors.append(f"{manifest_path}: field `{field}` must be a list")
    for field in ("artifacts", "cli_commands", "inputs", "outputs", "when_to_use", "do_not"):
        value = manifest.get(field)
        if value is not None and not isinstance(value, list):
            errors.append(f"{manifest_path}: field `{field}` must be a list")
    return errors


def _purpose_path(algorithm_id: str) -> Path:
    return PURPOSE_ROOT / f"{algorithm_id}.md"


def load_algorithms() -> list[dict]:
    algorithms: list[dict] = []
    errors: list[str] = []
    for manifest_path in sorted(FAMILIES_ROOT.glob("*/*.json")):
        spec_path = manifest_path.with_suffix(".md")
        manifest = read_json(manifest_path)
        errors.extend(_validate_manifest(manifest_path, manifest))
        manifest["manifest_path"] = str(manifest_path.relative_to(ROOT))
        manifest["spec_path"] = str(spec_path.relative_to(ROOT))
        manifest["preview"] = read_preview(spec_path)
        manifest["purpose_path"] = str(_purpose_path(str(manifest["id"])).relative_to(ROOT))
        algorithms.append(manifest)
    if errors:
        joined = "\n".join(errors)
        raise ValueError(f"substrate manifest validation failed:\n{joined}")
    return algorithms


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def render_agent_index(algorithms: list[dict]) -> str:
    families = defaultdict(list)
    for item in algorithms:
        families[item["family"]].append(item)

    lines = [
        GENERATED_NOTICE,
        "# Substrate Agent Index",
        "",
        f"- generated_at: {utc_now()}",
        f"- algorithm_count: {len(algorithms)}",
        f"- family_count: {len(families)}",
        "",
        "## Zoom 0 — Overview",
        "",
    ]
    for family in sorted(families):
        lines.extend(
            [
                f"- `{family}`: {len(families[family])} algorithms",
                f"  - {family_summary(family)}",
                f"  - browse: `context/substrate/families/{family}/INDEX.md`",
            ]
        )

    lines.extend(["", "## Zoom 1 — Families", ""])
    for family in sorted(families):
        lines.extend(
            [
                f"### {family.title()}",
                "",
                family_summary(family),
                "",
            ]
        )
        for item in sorted(families[family], key=lambda row: row["title"]):
            lines.append(f"- `{item['title']}` → `{item['id']}`")
        lines.append("")

    lines.extend(["## Zoom 2 — Algorithms", ""])
    for item in sorted(algorithms, key=lambda row: (row["family"], row["title"])):
        lines.extend(
            [
                f"### {item['title']}",
                "",
                f"- id: `{item['id']}`",
                f"- family: `{item['family']}`",
                f"- purpose: {item['purpose']}",
                f"- extracts: {', '.join(item['extracts'])}",
                f"- depends_on: {', '.join(item['depends_on']) if item['depends_on'] else 'none'}",
                f"- feeds_into: {', '.join(item['feeds_into']) if item['feeds_into'] else 'none'}",
                f"- spec: `{item['spec_path']}`",
                f"- manifest: `{item['manifest_path']}`",
                f"- purpose_artifact: `{item['purpose_path']}`",
            ]
        )
        if item.get("graph_layer"):
            lines.append(f"- graph_layer: `{item['graph_layer']}`")
        if item.get("code_module"):
            lines.append(f"- code_module: `{item['code_module']}`")
        if item["preview"]:
            lines.append(f"- preview: {item['preview']}")
        lines.append("")

    return "\n".join(lines)


def render_family_index(family: str, items: list[dict]) -> str:
    lines = [
        GENERATED_NOTICE,
        f"# {family.title()} Family Index",
        "",
        f"- generated_at: {utc_now()}",
        f"- algorithm_count: {len(items)}",
        "",
        family_summary(family),
        "",
    ]
    for item in sorted(items, key=lambda row: row["title"]):
        lines.extend(
            [
                f"## {item['title']}",
                "",
                f"- id: `{item['id']}`",
                f"- purpose: {item['purpose']}",
                f"- extracts: {', '.join(item['extracts'])}",
                f"- depends_on: {', '.join(item['depends_on']) if item['depends_on'] else 'none'}",
                f"- feeds_into: {', '.join(item['feeds_into']) if item['feeds_into'] else 'none'}",
                f"- spec: `{Path(item['spec_path']).name}`",
                f"- manifest: `{Path(item['manifest_path']).name}`",
                f"- purpose_artifact: `{Path(item['purpose_path']).name}`",
            ]
        )
        if item.get("graph_layer"):
            lines.append(f"- graph_layer: `{item['graph_layer']}`")
        if item.get("code_module"):
            lines.append(f"- code_module: `{item['code_module']}`")
        if item["preview"]:
            lines.append(f"- preview: {item['preview']}")
        lines.append("")
    return "\n".join(lines)


def render_registry(algorithms: list[dict]) -> dict:
    return {
        "generated_at": utc_now(),
        "count": len(algorithms),
        "algorithms": algorithms,
    }


def _render_list_section(title: str, items: list[str]) -> list[str]:
    if not items:
        return []
    lines = [f"## {title}", ""]
    lines.extend(f"- {item}" for item in items)
    lines.append("")
    return lines


def render_purpose_artifact(item: dict) -> str:
    spec_body = ""
    spec_path = ROOT / str(item.get("spec_path", ""))
    if spec_path.exists():
        spec_body = spec_path.read_text(encoding="utf-8").strip()
        if spec_body.startswith("<!--"):
            spec_body = "\n".join(spec_body.splitlines()[1:]).strip()

    lines = [
        GENERATED_NOTICE,
        f"# {item['title']}",
        "",
        f"- id: `{item['id']}`",
        f"- family: `{item['family']}`",
        f"- purpose: {item['purpose']}",
    ]
    if item.get("graph_layer"):
        lines.append(f"- graph_layer: `{item['graph_layer']}`")
    if item.get("code_module"):
        lines.append(f"- code_module: `{item['code_module']}`")
    if item.get("module_id"):
        lines.append(f"- module_id: `{item['module_id']}`")
    lines.extend(
        [
            f"- spec: `{item['spec_path']}`",
            f"- manifest: `{item['manifest_path']}`",
            "",
            "## Purpose",
            "",
            str(item["purpose"]),
            "",
        ]
    )
    lines.extend(_render_list_section("Extracts", list(item.get("extracts", []))))
    lines.extend(_render_list_section("Inputs", list(item.get("inputs", []))))
    lines.extend(_render_list_section("Outputs", list(item.get("outputs", []))))
    artifacts = item.get("artifacts", [])
    if artifacts:
        lines.extend(["## Artifacts", ""])
        for artifact in artifacts:
            if isinstance(artifact, dict):
                name = artifact.get("name", "artifact")
                path = artifact.get("path", "")
                purpose = artifact.get("purpose", "")
                lines.append(f"- **{name}** — `{path}`")
                if purpose:
                    lines.append(f"  - {purpose}")
            else:
                lines.append(f"- {artifact}")
        lines.append("")
    lines.extend(_render_list_section("CLI", list(item.get("cli_commands", []))))
    lines.extend(_render_list_section("Depends on", list(item.get("depends_on", []))))
    lines.extend(_render_list_section("Feeds into", list(item.get("feeds_into", []))))
    lines.extend(_render_list_section("When to use", list(item.get("when_to_use", []))))
    lines.extend(_render_list_section("Do not", list(item.get("do_not", []))))
    if spec_body:
        lines.extend(["## Spec", "", spec_body, ""])
    return "\n".join(lines).rstrip() + "\n"


def render_purpose_index(algorithms: list[dict]) -> dict:
    return {
        "generated_at": utc_now(),
        "count": len(algorithms),
        "algorithms": [
            {
                "id": item["id"],
                "title": item["title"],
                "family": item["family"],
                "graph_layer": item.get("graph_layer"),
                "code_module": item.get("code_module"),
                "module_id": item.get("module_id"),
                "purpose_path": item["purpose_path"],
                "spec_path": item["spec_path"],
                "manifest_path": item["manifest_path"],
            }
            for item in algorithms
        ],
    }


def render_browse_map(algorithms: list[dict]) -> dict:
    families: dict[str, dict] = {}
    for item in algorithms:
        family = families.setdefault(
            item["family"],
            {
                "summary": family_summary(item["family"]),
                "algorithms": [],
            },
        )
        family["algorithms"].append(
            {
                "id": item["id"],
                "title": item["title"],
                "purpose": item["purpose"],
                "graph_layer": item.get("graph_layer"),
                "code_module": item.get("code_module"),
                "module_id": item.get("module_id"),
                "purpose_path": item["purpose_path"],
                "spec_path": item["spec_path"],
                "manifest_path": item["manifest_path"],
            }
        )
    return {
        "generated_at": utc_now(),
        "families": families,
    }


def refresh() -> None:
    algorithms = load_algorithms()
    PURPOSE_ROOT.mkdir(parents=True, exist_ok=True)
    for item in algorithms:
        write_text(_purpose_path(str(item["id"])), render_purpose_artifact(item))
    write_text(
        SUBSTRATE_ROOT / "generated" / "purpose-index.json",
        json.dumps(render_purpose_index(algorithms), indent=2, ensure_ascii=False),
    )
    write_text(SUBSTRATE_ROOT / "AGENT_INDEX.md", render_agent_index(algorithms))
    write_text(
        SUBSTRATE_ROOT / "registry.json",
        json.dumps(render_registry(algorithms), indent=2, ensure_ascii=False),
    )
    write_text(
        SUBSTRATE_ROOT / "browse_map.json",
        json.dumps(render_browse_map(algorithms), indent=2, ensure_ascii=False),
    )

    grouped: dict[str, list[dict]] = defaultdict(list)
    for item in algorithms:
        grouped[item["family"]].append(item)
    for family, items in grouped.items():
        write_text(FAMILIES_ROOT / family / "INDEX.md", render_family_index(family, items))


def fingerprint() -> str:
    digest = hashlib.sha256()
    for path in sorted(FAMILIES_ROOT.glob("*/*")):
        if path.suffix not in {".json", ".md"}:
            continue
        if path.name == "INDEX.md":
            continue
        digest.update(str(path.relative_to(ROOT)).encode("utf-8"))
        stat = path.stat()
        digest.update(str(stat.st_mtime_ns).encode("utf-8"))
        digest.update(str(stat.st_size).encode("utf-8"))
    return digest.hexdigest()


def watch(interval: float) -> None:
    refresh()
    last = fingerprint()
    print(f"[substrate-index] watching {FAMILIES_ROOT} every {interval:.1f}s")
    while True:
        time.sleep(interval)
        current = fingerprint()
        if current == last:
            continue
        refresh()
        last = current
        print(f"[substrate-index] refreshed at {utc_now()}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate browse indexes for the substrate abstraction library.")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("refresh")
    watch_parser = sub.add_parser("watch")
    watch_parser.add_argument("--interval", type=float, default=2.0)
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    if args.command == "refresh":
        refresh()
        return 0
    if args.command == "watch":
        watch(args.interval)
        return 0
    raise ValueError(args.command)


if __name__ == "__main__":
    raise SystemExit(main())
